using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using Windows.Foundation;
using Windows.Foundation.Collections;
using Windows.UI.Text;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Controls.Primitives;
using Windows.UI.Xaml.Data;
using Windows.UI.Xaml.Input;
using Windows.UI.Xaml.Media;
using Windows.UI.Xaml.Navigation;

namespace Marbles
{
	public sealed partial class FunctionCall : UserControl
	{
		public FunctionCall()
		{
			this.InitializeComponent();
		}

        public static event EventHandler SomethingChanged;

        /// <summary>
        /// Event invoked when the button to add a parameter is clicked.
        /// Creates a new <see cref="Values"/> object and adds the parameter visually.
        /// Invokes the <see cref="SomethingChanged"/> event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void AddParameter(object sender, RoutedEventArgs e)
		{
            SomethingChanged?.Invoke(this, EventArgs.Empty);

            Grid containerGrid = new Grid();
			Values newValue = new Values();
			containerGrid.Children.Add(newValue);

            Parameters.Items.Add(containerGrid);
		}

        /// <summary>
        /// Adds to <see cref="Utilities.linesOfCode"/> the code generated by this block.
        /// Called by blocks that contain this UserControl.
        /// </summary>
        public void PrintCode()
        {
            ((CodeLine)Utilities.linesOfCode[Utilities.linesOfCodeCount-1]).content += " call " + FunctionNameTextBox.Text + "(";
            bool firstParam = true;
            foreach (Grid holder in Parameters.Items)
            {
				foreach (Object val in holder.Children)
				{
					if (firstParam)
					{
						firstParam = false;
						PrintParameterCode(val);
					}
					else
					{
						((CodeLine)Utilities.linesOfCode[Utilities.linesOfCodeCount - 1]).content += ", ";
						PrintParameterCode(val);
					}
				}
            }
            ((CodeLine)Utilities.linesOfCode[Utilities.linesOfCodeCount-1]).content += ")";
        }

        /// <summary>
        /// Calls in <see cref="PrintCode"/> the PrintCode method for each parameter object.
        /// </summary>
        /// <param name="obj"></param>
		private void PrintParameterCode(Object obj)
		{
			var varType = obj.GetType();
			if (varType == typeof(AssetFunction))
			{
				((AssetFunction)obj).PrintCode();
			}
			else if (varType == typeof(AssetAttribute))
			{
				((AssetAttribute)obj).PrintCode();
			}
			else if (varType == typeof(ConstantBoolean))
			{
				((ConstantBoolean)obj).PrintCode();
			}
			else if (varType == typeof(BooleanExpression))
			{
				((BooleanExpression)obj).PrintCode();
			}
			else if (varType == typeof(Parenthesis))
			{
				((Parenthesis)obj).PrintCode();
			}
			else if (varType == typeof(Negative))
			{
				((Negative)obj).PrintCode();
			}
			else if (varType == typeof(FunctionCall))
			{
				((FunctionCall)obj).PrintCode();
			}
			else if (varType == typeof(MathExpression))
			{
				((MathExpression)obj).PrintCode();
			}
			else if (varType == typeof(ConstantNumber))
			{
				((ConstantNumber)obj).PrintCode();
			}
			else if (varType == typeof(ConstantText))
			{
				((ConstantText)obj).PrintCode();
			}
			else if (varType == typeof(VariableCall))
			{
				((VariableCall)obj).PrintCode();
			}
		}

        /// <summary>
        /// Event invoked when the text in function name's TextBox changes.
        /// Verifies that the name entered for the function is valid.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		private void FunctionNameTextBox_TextChanged(object sender, TextChangedEventArgs e)
		{
            SomethingChanged?.Invoke(this, EventArgs.Empty);

            var textBox = sender as TextBox;
			if (textBox.Text != "")
			{
				if (textBox.SelectionStart == 1)
				{
					if (!(Char.IsLetter(textBox.Text[textBox.SelectionStart - 1]) ||
					textBox.Text[textBox.SelectionStart - 1] == '_'))
					{
						int pos = textBox.SelectionStart - 1;
						textBox.Text = textBox.Text.Remove(pos, 1);
						textBox.SelectionStart = pos;
					}
				}
				else
				{
					if (!(Char.IsLetterOrDigit(textBox.Text[textBox.SelectionStart - 1]) ||
					textBox.Text[textBox.SelectionStart - 1] == '_'))
					{
						int pos = textBox.SelectionStart - 1;
						textBox.Text = textBox.Text.Remove(pos, 1);
						textBox.SelectionStart = pos;
					}
				}
			}
		}
	}
}
