using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using Windows.Foundation;
using Windows.Foundation.Collections;
using Windows.UI.Text;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Controls.Primitives;
using Windows.UI.Xaml.Data;
using Windows.UI.Xaml.Input;
using Windows.UI.Xaml.Media;
using Windows.UI.Xaml.Navigation;

namespace Marbles
{
	public sealed partial class CreateFunction : UserControl
	{
		public CreateFunction()
		{
			this.InitializeComponent();
		}

        /// <summary>
        /// Event invoked when the button to add a new parameter is clicked.
        /// Invokes the <see cref="SomethingChanged"/> event and initializes
        /// a new ComboBox and TextBox for the new parameter field.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void AddParameter(object sender, RoutedEventArgs e)
		{
            SomethingChanged?.Invoke(this, EventArgs.Empty);
            var DataType = new ComboBox
            {
                FontFamily = new FontFamily("Segoe UI Light"),
                FontWeight = FontWeights.Light,
                HorizontalContentAlignment = HorizontalAlignment.Center,
                HorizontalAlignment = HorizontalAlignment.Stretch,
                VerticalAlignment = VerticalAlignment.Center,
                Margin = new Thickness(0, 0, -10, 0),
                Width = double.NaN,
            };

            DataType.SelectionChanged += DataType_SelectionChanged;

            ComboBoxItem number = new ComboBoxItem
            {
                Content = "number",
                TabIndex = 0
            };
            ComboBoxItem text = new ComboBoxItem
            {
                Content = "text",
                TabIndex = 1
            };
            ComboBoxItem boolean = new ComboBoxItem
            {
                Content = "boolean",
                TabIndex = 2
            };

            DataType.Items.Add(number);
            DataType.Items.Add(text);
            DataType.Items.Add(boolean);

            DataType.SelectedIndex = 0;

            Parameters.Items.Add(DataType);

            var ParameterName = new TextBox
            {
                FontFamily = new FontFamily("Segoe UI Light"),
                FontWeight = FontWeights.Light,
                HorizontalContentAlignment = HorizontalAlignment.Center,
                HorizontalAlignment = HorizontalAlignment.Stretch,
                VerticalAlignment = VerticalAlignment.Center,
                TextAlignment = TextAlignment.Center,
                PlaceholderText = "Parameter Here",
                Width = double.NaN,
                InputScope = new InputScope
                {
                    Names =
                    {
                        new InputScopeName(InputScopeNameValue.Text)
                    }
                }
            };

            ParameterName.TextChanged += ParameterName_TextChanged;

            Parameters.Items.Add(ParameterName);
		}

        /// <summary>
        /// Event invoked when the name of a parameter changes.
        /// Invokes the <see cref="SomethingChanged"/> event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void ParameterName_TextChanged(object sender, TextChangedEventArgs e)
        {
            SomethingChanged?.Invoke(this, EventArgs.Empty);
        }

        /// <summary>
        /// Event invoked when the selection of the data type of a parameter changes.
        /// Invokes the <see cref="SomethingChanged"/> event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void DataType_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            SomethingChanged?.Invoke(this, EventArgs.Empty);
        }

        /// <summary>
        /// Adds to <see cref="Utilities.linesOfCode"/> the code generated by this block.
        /// Called by blocks that contain this UserControl.
        /// </summary>
        public void PrintCode()
        {
			CleanPossibleError();
			string funcType = ((ComboBoxItem)(functionType.SelectedItem)).Content.ToString();
            if (funcType == "boolean") funcType = "bool";

            Utilities.linesOfCode.Add(new CodeLine("function " + funcType  + " " + functionID.Text + "(", this, Utilities.linesOfCodeCount + 1));
            Utilities.linesOfCodeCount++;
            bool firstParam = true;
            foreach (var item in Parameters.Items)
            {
                if (item.GetType() == typeof(ComboBox))
                {
                    if (firstParam)
                    {
                        firstParam = false;
                    }
                    else
                    {
                        ((CodeLine)Utilities.linesOfCode[Utilities.linesOfCodeCount-1]).content += ", ";
                    }

                    string dataTypeSelected = ((ComboBoxItem)(((ComboBox)item).SelectedItem)).Content.ToString();

                    if (dataTypeSelected == "boolean")
                    {
                        dataTypeSelected = "bool";
                    }

                    ((CodeLine)Utilities.linesOfCode[Utilities.linesOfCodeCount-1]).content += dataTypeSelected + " ";
                }
                else
                {
                    ((CodeLine)Utilities.linesOfCode[Utilities.linesOfCodeCount-1]).content += ((TextBox)item).Text;
                }
            }

            ((CodeLine)Utilities.linesOfCode[Utilities.linesOfCodeCount-1]).content += ") {";
            VariableListViewContainer.PrintCode();
            InstructionListViewContainer.PrintCode();
            Utilities.linesOfCode.Add(new CodeLine("}", this, Utilities.linesOfCodeCount + 1));
            Utilities.linesOfCodeCount++;
        }

        /// <summary>
        /// Event invoked when the value of the name of the function being created is changed.
        /// Invokes the <see cref="SomethingChanged"/> event and verifies that the input is valid.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		private void functionID_TextChanged(object sender, TextChangedEventArgs e)
		{
            SomethingChanged?.Invoke(this, EventArgs.Empty);
            var textBox = sender as TextBox;
			if (textBox.Text != "")
			{
				if (textBox.SelectionStart == 1)
				{
					if (!(Char.IsLetter(textBox.Text[textBox.SelectionStart - 1]) ||
					textBox.Text[textBox.SelectionStart - 1] == '_'))
					{
						int pos = textBox.SelectionStart - 1;
						textBox.Text = textBox.Text.Remove(pos, 1);
						textBox.SelectionStart = pos;
					}
				}
				else
				{
					if (!(Char.IsLetterOrDigit(textBox.Text[textBox.SelectionStart - 1]) ||
					textBox.Text[textBox.SelectionStart - 1] == '_'))
					{
						int pos = textBox.SelectionStart - 1;
						textBox.Text = textBox.Text.Remove(pos, 1);
						textBox.SelectionStart = pos;
					}
				}
			}
		}

        public static event EventHandler SomethingChanged;

        /// <summary>
        /// Event invoked when the selection of the return data type of the function changes.
        /// Invokes the <see cref="SomethingChanged"/> event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void functionType_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            SomethingChanged?.Invoke(this, EventArgs.Empty);
        }

        /// <summary>
        /// Shows the error signal of this block.
        /// Called when an error is caused by the lines of code this block generated.
        /// </summary>
        /// <param name="errorColor"></param>
		public void SetError(Brush errorColor)
		{
			ErrorEllipseGrid.Padding = new Thickness(5.0);
			ErrorEllipse.Height = 10;
			ErrorEllipse.Width = 10;
			ErrorEllipse.Fill = errorColor;
		}

        /// <summary>
        /// Removes the error signal of this block.
        /// Called before compiling.
        /// </summary>
		public void CleanPossibleError()
		{
			ErrorEllipseGrid.Padding = new Thickness(0.0);
			ErrorEllipse.Height = 0;
			ErrorEllipse.Width = 0;
		}
	}
}
